### ISSUE TITLE
Different primary years used for social.csv in CAUSALITY and PREDICTION

### ISSUE THREAD

**Issue by jrnold** [kosukeimai/qss#13]
In `CAUSALITY/social.csv` the primary year is 2006 in variable `primary2006`, while in `PREDICTION/social.csv` the primary year is 2008 in variable `primary2008`. Since these should both be the same data from 

>  Alan S. Gerber, Donald P. Green, and Christopher W. Larimer. (2008). “Social Pressure and Voter > Turnout: Evidence from a Large-Scale Field Experiment.” American Political Science Review, Vol. > 102, No. 1, pp. 33–48.

the primary year should be 2006 in both. This also affects the code and text in Section 4.3 that refers to the 2008 primary and `primary2008` variable.

**Comment by kosukeimai** [comment]
Thanks for noticing this typo.  Unfortunately, the book is in press but we will fix it in the next printing.  Both the data set and code will be fixed once the second printing comes out.

**Comment by kosukeimai** [comment]
This issue has been fixed for the second printing in the `secondprinting` branch
