### ISSUE TITLE
Repackage QSS data and code as an R package

### ISSUE THREAD

**Issue by jrnold** [kosukeimai/qss#16]
It's a bit awkward to work with the csv's in their current form and to write reproducible code. Have you considered releasing an R package of the data instead or in addition to this?  I quickly put together an R package with all the QSS data: https://github.com/jrnold/qss-data. All datasets as either built-in datasets to load, or files accessible through `system.file`, the scripts are included as demos for the package, and the package builds its own website using [pkgdown](https://github.com/hadley/pkgdown). Right now the entire thing is scripted to build from the latest version of this repository. The only thing that is missing is metadata about variables.

**Comment by kosukeimai** [comment]
Thanks for this.  The answer to your question is yes.  If you are interested in collaborating, send me an email.
