### ISSUE TITLE
Issue installing QSS package

### ISSUE THREAD

**Issue by MTDTMFH** [kosukeimai/qss#28]
I have the following error when I install the packages - tried on all three links listed on the website but to no avail..

Is there a way to install without the 'uncertainty.Rmd' file which seems to be causing the problem? Any other fixes to get started would be greatly appreciated as I can't seem to find anything googling these errors.

Error: Failed to install 'qss' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- finished re-building ‘probability.Rmd’
E> 
E> --- re-building ‘uncertainty.Rmd’ using rmarkdown
E> --- finished re-building ‘uncertainty.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘discovery.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by MTDTMFH** [comment]
library("devtools")
install_github("kosukeimai/qss-package", build_vignettes = TRUE)

Thanks in advance

**Comment by kosukeimai** [comment]
Thanks for noticing this.  It's been fixed.

**Comment by MTDTMFH** [comment]
Thanks for fixing the issue promptly! All sorted now :)
