### ISSUE TITLE
Text typo in sentence on critical value (sec 7.1.3)

### ISSUE THREAD

**Issue by kuriwaki** [kosukeimai/qss#31]
Sec 7.1.3 and p.372 in the tidyverse version of QSS (also the non-tidyverse version) says 

> $z_{\alpha/2}$ is the critical value, which equals the $(1 − \alpha/2)$ quantile of the standard normal distribution such that $P(Z> \alpha/2) = 1 -P(Z \leq \alpha/2) = 1-\alpha/2$, where Z is a standard normal random variable."

I think the last part should be $=\alpha/2$ instead of 1 minus it? P(Z > z_{0.025}) = P(Z > 1.96) = 0.025.

**Comment by kosukeimai** [comment]
Thanks @kuriwaki !  I've updated the errata accordingly.
